title: "migueldnt.dev"
tagline: Portafolio y sitio personal
description: >-
    Software Developer. #GIS #Marketing 
twitter:
    username: miguel_dnt



url: "https://migueldnt.dev"
repo: "https://github.com/migueldanto/migueldnt.dev"

#theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag

exclude:
    - README.md
    - .jekyll-cache
    - docker-compose.yml
    - docker-compose-dev.yml    
    - .gitkeep